import client from './client';

export const accountsApi = {
  seedChart: () => client.post('/accounts/seed-chart').then((r) => r.data),
  ledgers: (params) => client.get('/accounts/ledgers', { params }).then((r) => r.data),
  ledgerTree: (params) => client.get('/accounts/ledgers/tree', { params }).then((r) => r.data),
  ledgerReport: (params) => client.get('/accounts/reports/ledger', { params }).then((r) => r.data),
  ledgerBalance: (id) => client.get(`/accounts/ledgers/${id}/balance`).then((r) => r.data),
  nextLedgerCode: (type) => client.get('/accounts/ledgers/next-code', { params: { type } }).then((r) => r.data),
  paymentMethodLedgers: () => client.get('/accounts/payment-method-ledgers').then((r) => r.data),
  paymentMethods: (params) => client.get('/accounts/payment-methods', { params }).then((r) => r.data),
  createPaymentMethod: (data) => client.post('/accounts/payment-methods', data).then((r) => r.data),
  updatePaymentMethod: (id, data) => client.patch(`/accounts/payment-methods/${id}`, data).then((r) => r.data),
  postingRules: () => client.get('/accounts/posting-rules').then((r) => r.data),
  updatePostingRules: (data) => client.put('/accounts/posting-rules', data).then((r) => r.data),
  createLedger: (data) => client.post('/accounts/ledgers', data).then((r) => r.data),
  updateLedger: (id, data) => client.patch(`/accounts/ledgers/${id}`, data).then((r) => r.data),
  canDeleteLedger: (id) => client.get(`/accounts/ledgers/${id}/can-delete`).then((r) => r.data),
  deleteLedger: (id) => client.delete(`/accounts/ledgers/${id}`).then((r) => r.data),
  mergeLedgers: (data) => client.post('/accounts/ledgers/merge', data).then((r) => r.data),
  journals: (params) => client.get('/accounts/journal-entries', { params }).then((r) => r.data),
  journal: (id) => client.get(`/accounts/journal-entries/${id}`).then((r) => r.data),
  createJournal: (data) => client.post('/accounts/journal-entries', data).then((r) => r.data),
  createCustomerReceipt: (data) => client.post('/accounts/customer-receipts', data).then((r) => r.data),
  createVoucher: (kind, data) => client.post(`/accounts/${kind}`, data).then((r) => r.data),
  invoices: (params) => client.get('/accounts/invoices', { params }).then((r) => r.data),
  creditNotes: (params) => client.get('/accounts/credit-notes', { params }).then((r) => r.data),
  createCreditNote: (data) => client.post('/accounts/credit-notes', data).then((r) => r.data),
  reminders: (params) => client.get('/accounts/reminders', { params }).then((r) => r.data),
  createReminder: (data) => client.post('/accounts/reminders', data).then((r) => r.data),
  reconciliation: (params) => client.get('/accounts/reconciliation', { params }).then((r) => r.data),
  reconcile: (data) => client.put('/accounts/reconciliation', data).then((r) => r.data),
  report: (name, params) => client.get(`/accounts/reports/${name}`, { params }).then((r) => r.data),
};
