// FILE: /frontend/src/pages/hrm/Payroll.jsx

import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import {
  ChevronLeftIcon, ChevronRightIcon, BanknotesIcon, PlusIcon, TrashIcon, PrinterIcon,
} from '@heroicons/react/24/outline';
import {
  usePayroll, useGeneratePayroll, useUpdatePayslip, usePayslipStatus,
} from '../../api/hrm';
import { useAuthStore } from '../../store/authStore';
import {
  SectionCard, StatTile, Pill, EmptyState, Spinner, SlideOver, Field,
  PAYSLIP_STATUS, fmtMoney, fmtMonthLabel, currentMonthStr,
} from './hrmUi';

function shiftMonth(month, delta) {
  const [y, m] = month.split('-').map((n) => parseInt(n, 10));
  const d = new Date(y, m - 1 + delta, 1);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
}

function esc(value) {
  return String(value ?? '').replace(/[&<>"']/g, (c) => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
  ));
}

function printPayslip(slip, agencyName, month) {
  const lines = (items, sign) => (items || []).map((i) => `<tr><td>${esc(i.label)}</td><td style="text-align:right">${sign}${esc(fmtMoney(i.amount))}</td></tr>`).join('');
  const html = `<!doctype html><html><head><title>Payslip ${esc(slip.agent?.name)} ${esc(month)}</title>
  <style>
    body{font-family:'Manrope',system-ui,Arial,sans-serif;color:#171717;padding:40px;max-width:680px;margin:auto}
    h1{font-size:20px;margin:0} .muted{color:#737373;font-size:13px}
    table{width:100%;border-collapse:collapse;margin-top:8px;font-size:14px}
    td{padding:6px 0;border-bottom:1px solid #eee}
    .head{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #171717;padding-bottom:16px;margin-bottom:20px}
    .net{display:flex;justify-content:space-between;font-size:18px;font-weight:800;margin-top:18px;padding-top:14px;border-top:2px solid #171717}
    .grid{display:flex;gap:24px;margin:16px 0;font-size:13px}
  </style></head><body>
  <div class="head"><div><h1>${esc(agencyName || 'Payslip')}</h1><p class="muted">Payslip · ${esc(fmtMonthLabel(month))}</p></div>
  <div style="text-align:right"><strong>${esc(slip.agent?.name)}</strong><br/><span class="muted">${esc(slip.agent?.email)}</span></div></div>
  <div class="grid"><div><span class="muted">Working days</span><br/><strong>${slip.workingDays}</strong></div>
  <div><span class="muted">Paid days</span><br/><strong>${slip.paidDays}</strong></div>
  <div><span class="muted">Unpaid days</span><br/><strong>${slip.unpaidDays}</strong></div></div>
  <table><tr><td><strong>Earnings</strong></td><td></td></tr>
  <tr><td>Base salary</td><td style="text-align:right">${fmtMoney(slip.baseSalary)}</td></tr>
  ${lines(slip.earnings, '+')}</table>
  <table style="margin-top:16px"><tr><td><strong>Deductions</strong></td><td></td></tr>
  <tr><td>Loss of pay (${slip.unpaidDays} days)</td><td style="text-align:right">-${fmtMoney(slip.lossOfPay)}</td></tr>
  ${lines(slip.deductions, '-')}</table>
  <div class="net"><span>Net pay</span><span>${fmtMoney(slip.netPay)}</span></div>
  <p class="muted" style="margin-top:30px">Generated by Wayon HRM · This is a system-generated payslip.</p>
  </body></html>`;
  const w = window.open('', '_blank');
  if (!w) { toast.error('Allow pop-ups to print'); return; }
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 300);
}

function LineEditor({ title, items, onChange, sign }) {
  const add = () => onChange([...(items || []), { label: '', amount: 0 }]);
  const update = (i, k, v) => onChange(items.map((it, idx) => (idx === i ? { ...it, [k]: v } : it)));
  const remove = (i) => onChange(items.filter((_, idx) => idx !== i));
  return (
    <div>
      <div className="mb-2 flex items-center justify-between">
        <p className="text-xs font-bold uppercase tracking-wide text-neutral-500">{title}</p>
        <button onClick={add} className="shell-button-ghost text-xs"><PlusIcon className="h-3.5 w-3.5" /> Add</button>
      </div>
      <div className="space-y-2">
        {(items || []).map((it, i) => (
          <div key={i} className="flex items-center gap-2">
            <input value={it.label} onChange={(e) => update(i, 'label', e.target.value)} placeholder="Label" className="shell-input-rect flex-1 py-2 text-sm" />
            <div className="relative w-32">
              <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-xs text-neutral-400">{sign}₹</span>
              <input type="number" value={it.amount} onChange={(e) => update(i, 'amount', Number(e.target.value) || 0)} className="shell-input-rect py-2 pl-8 text-sm tabular-nums" />
            </div>
            <button onClick={() => remove(i)} className="shell-button-ghost text-rose-500"><TrashIcon className="h-4 w-4" /></button>
          </div>
        ))}
        {!(items || []).length && <p className="text-xs text-neutral-400">None added.</p>}
      </div>
    </div>
  );
}

function PayslipDetail({ slip, month, onClose }) {
  const agency = useAuthStore((s) => s.agency);
  const update = useUpdatePayslip();
  const status = usePayslipStatus();
  const [earnings, setEarnings] = useState([]);
  const [deductions, setDeductions] = useState([]);

  useEffect(() => {
    if (slip) { setEarnings(slip.earnings || []); setDeductions(slip.deductions || []); }
  }, [slip]);

  if (!slip) return null;
  const locked = slip.status === 'PAID';

  const save = () => update.mutate(
    { id: slip.id, earnings, deductions },
    { onSuccess: () => toast.success('Payslip updated'), onError: (e) => toast.error(e.response?.data?.error || 'Failed') }
  );
  const setStatus = (action, label) => status.mutate(
    { id: slip.id, action },
    { onSuccess: () => toast.success(label), onError: (e) => toast.error(e.response?.data?.error || 'Failed') }
  );

  return (
    <SlideOver
      open={Boolean(slip)}
      onClose={onClose}
      title={slip.agent?.name}
      subtitle={`Payslip · ${fmtMonthLabel(month)}`}
      widthClass="max-w-lg"
      footer={
        <div className="flex flex-wrap justify-between gap-2">
          <button onClick={() => printPayslip(slip, agency?.name, month)} className="shell-button-secondary"><PrinterIcon className="h-4 w-4" /> Print</button>
          <div className="flex gap-2">
            {!locked && <button onClick={save} disabled={update.isPending} className="shell-button-secondary">Save</button>}
            {slip.status === 'DRAFT' && <button onClick={() => setStatus('finalize', 'Finalized')} className="shell-button-primary">Finalize</button>}
            {slip.status === 'FINALIZED' && (
              <button onClick={() => setStatus('mark-paid', 'Marked paid')} className="inline-flex min-h-11 items-center gap-2 rounded-[var(--radius-md)] bg-[#00A884] px-4 text-sm font-semibold text-white hover:bg-[#019174]">Mark paid</button>
            )}
          </div>
        </div>
      }
    >
      <div className="space-y-5">
        <div className="rounded-[var(--radius-md)] bg-neutral-900 p-5 text-white">
          <p className="text-xs font-medium uppercase tracking-wide text-neutral-400">Net pay</p>
          <p className="mt-1 text-3xl font-extrabold tabular-nums">{fmtMoney(slip.netPay)}</p>
          <div className="mt-3"><Pill map={PAYSLIP_STATUS} status={slip.status} /></div>
        </div>

        <div className="grid grid-cols-3 gap-2 text-center">
          <div className="rounded-lg bg-neutral-50 p-3"><p className="text-lg font-bold tabular-nums text-neutral-900">{slip.workingDays}</p><p className="text-[10px] font-semibold uppercase text-neutral-400">Working</p></div>
          <div className="rounded-lg bg-emerald-50 p-3"><p className="text-lg font-bold tabular-nums text-emerald-700">{slip.paidDays}</p><p className="text-[10px] font-semibold uppercase text-emerald-600">Paid</p></div>
          <div className="rounded-lg bg-rose-50 p-3"><p className="text-lg font-bold tabular-nums text-rose-700">{slip.unpaidDays}</p><p className="text-[10px] font-semibold uppercase text-rose-600">Unpaid</p></div>
        </div>

        <div className="flex items-center justify-between rounded-[var(--radius-md)] border border-neutral-200 px-4 py-3 text-sm">
          <span className="font-medium text-neutral-600">Base salary</span>
          <span className="font-bold tabular-nums text-neutral-900">{fmtMoney(slip.baseSalary)}</span>
        </div>
        <div className="flex items-center justify-between rounded-[var(--radius-md)] border border-rose-100 bg-rose-50/50 px-4 py-3 text-sm">
          <span className="font-medium text-rose-600">Loss of pay · {slip.unpaidDays} days</span>
          <span className="font-bold tabular-nums text-rose-700">−{fmtMoney(slip.lossOfPay)}</span>
        </div>

        {locked ? (
          <p className="text-xs text-neutral-400">This payslip is paid and locked.</p>
        ) : (
          <>
            <LineEditor title="Additional earnings" items={earnings} onChange={setEarnings} sign="+" />
            <LineEditor title="Other deductions" items={deductions} onChange={setDeductions} sign="−" />
          </>
        )}
      </div>
    </SlideOver>
  );
}

export default function Payroll() {
  const [month, setMonth] = useState(currentMonthStr());
  const { data, isLoading } = usePayroll(month);
  const generate = useGeneratePayroll();
  const [active, setActive] = useState(null);

  const run = () => generate.mutate(month, {
    onSuccess: () => toast.success('Payroll generated'),
    onError: (e) => toast.error(e.response?.data?.error || 'Failed'),
  });

  const slips = data?.payslips || [];

  return (
    <div className="space-y-5">
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <StatTile label="Employees" value={data?.count ?? 0} icon={BanknotesIcon} />
        <StatTile label="Gross" value={fmtMoney(data?.totals?.gross)} />
        <StatTile label="Deductions (LOP)" value={fmtMoney(data?.totals?.lop)} accent="rose" />
        <StatTile label="Net payout" value={fmtMoney(data?.totals?.net)} accent="green" />
      </div>

      <SectionCard
        title="Payroll"
        subtitle={fmtMonthLabel(month)}
        actions={
          <div className="flex items-center gap-2">
            <div className="flex items-center gap-1">
              <button onClick={() => setMonth(shiftMonth(month, -1))} className="shell-button-ghost h-9 w-9 p-0"><ChevronLeftIcon className="h-4 w-4" /></button>
              <button onClick={() => setMonth(shiftMonth(month, 1))} disabled={month >= currentMonthStr()} className="shell-button-ghost h-9 w-9 p-0 disabled:opacity-30"><ChevronRightIcon className="h-4 w-4" /></button>
            </div>
            <button onClick={run} disabled={generate.isPending} className="shell-button-primary">
              {generate.isPending ? 'Generating…' : slips.length ? 'Re-generate' : 'Generate payroll'}
            </button>
          </div>
        }
      >
        {isLoading ? <Spinner /> : !slips.length ? (
          <EmptyState
            icon={BanknotesIcon}
            title="No payroll for this month"
            hint="Generate draft payslips from attendance & approved leave, then review each before paying."
            action={<button onClick={run} className="shell-button-primary">Generate payroll</button>}
          />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[680px] text-sm">
              <thead>
                <tr className="border-b border-neutral-200 text-left text-[11px] font-bold uppercase tracking-wide text-neutral-400">
                  <th className="py-2.5 pr-3">Employee</th>
                  <th className="px-3 py-2.5 text-center">Paid / Unpaid</th>
                  <th className="px-3 py-2.5 text-right">Base</th>
                  <th className="px-3 py-2.5 text-right">LOP</th>
                  <th className="px-3 py-2.5 text-right">Net</th>
                  <th className="px-3 py-2.5">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-neutral-100">
                {slips.map((s) => (
                  <tr key={s.id} onClick={() => setActive(s)} className="cursor-pointer transition hover:bg-neutral-50">
                    <td className="py-3 pr-3 font-semibold text-neutral-900">{s.agent?.name}</td>
                    <td className="px-3 py-3 text-center tabular-nums text-neutral-600">{s.paidDays} / {s.unpaidDays}</td>
                    <td className="px-3 py-3 text-right tabular-nums text-neutral-600">{fmtMoney(s.baseSalary)}</td>
                    <td className="px-3 py-3 text-right tabular-nums text-rose-600">−{fmtMoney(s.lossOfPay)}</td>
                    <td className="px-3 py-3 text-right font-bold tabular-nums text-neutral-900">{fmtMoney(s.netPay)}</td>
                    <td className="px-3 py-3"><Pill map={PAYSLIP_STATUS} status={s.status} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </SectionCard>

      <PayslipDetail slip={active} month={month} onClose={() => setActive(null)} />
    </div>
  );
}
